FROM jsschrepping/r_docker:jss_R432_bioc318

MAINTAINER Jonas Schulte-Schrepping (jsschrepping) & Rainer Knoll

#############
### CONDA ###

ENV miniconda_bin_dir="/opt/miniconda/bin"
ENV PATH="${miniconda_bin_dir}:${PATH}"

# Install miniconda following https://stackoverflow.com/questions/58269375/how-to-install-packages-with-miniconda-in-dockerfile & https://github.com/tschaffter/rstudio/blob/main/Dockerfile
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.1.2-0-Linux-x86_64.sh \
    && bash Miniconda3-py310_24.1.2-0-Linux-x86_64.sh \
       -b \
       -p /opt/miniconda \
    && rm -f Miniconda3-py310_24.1.2-0-Linux-x86_64.sh \
    && conda --version

# Update conda
RUN conda update -n base -c defaults conda

# Set channels
RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge
RUN conda config --add channels rapidsai
RUN conda config --add channels nvidia

# Conda Packages
# install cytoSig & dependencies
RUN conda install -c conda-forge xlsxwriter=3.1.9
RUN conda install -c conda-forge gsl=2.6

# install leidenalg und louvain (based on error described here: https://stackoverflow.com/questions/77617946/solve-conda-libmamba-solver-libarchive-so-19-error-after-updating-conda-to-23)
RUN conda install -n base libarchive -c main --force-reinstall --solver classic 
RUN conda install -c conda-forge leidenalg==0.10.2
RUN conda install -c conda-forge louvain==0.8.2

RUN conda install -c rapidsai rapids=24.02.00
RUN conda install -c conda-forge cuda-version==11.4
RUN conda install -c rapidsai rmm==24.02.00
RUN conda install -c conda-forge cudnn==8.9.7.29
RUN conda install -c conda-forge cutensor==2.0.1.2
RUN conda install -c conda-forge cusparselt==0.4.0.7
RUN conda install -c conda-forge fa2==0.3.5
RUN conda install -c conda-forge jupyterlab==4.1.5

###################
### INSTALL PIP ###

# update pip
RUN /opt/miniconda/bin/python -m pip3 install --upgrade pip

# PIP packages
RUN /opt/miniconda/bin/python -m pip3 install openpyxl==3.0.9
RUN /opt/miniconda/bin/python -m pip3 install data-significance==1.3
RUN /opt/miniconda/bin/python -m pip3 install CytoSig==0.0.3
RUN /opt/miniconda/bin/python -m pip3 install numpy==1.26.4
RUN /opt/miniconda/bin/python -m pip3 install pandas==2.2.1
RUN /opt/miniconda/bin/python -m pip3 install scipy==1.12.0
RUN /opt/miniconda/bin/python -m pip3 install scikit-misc==0.3.1
RUN /opt/miniconda/bin/python -m pip3 install MACS3==3.0.1
RUN /opt/miniconda/bin/python -m pip3 install scanpy==1.10.0
RUN /opt/miniconda/bin/python -m pip3 install scvelo==0.3.2
RUN /opt/miniconda/bin/python -m pip3 install velovae==0.1.2
RUN /opt/miniconda/bin/python -m pip3 install cellrank==2.0.3
RUN /opt/miniconda/bin/python -m pip3 install scFates==1.0.7
RUN /opt/miniconda/bin/python -m pip3 install scrublet==0.2.3
RUN /opt/miniconda/bin/python -m pip3 install cellphonedb==5.0.0
RUN /opt/miniconda/bin/python -m pip3 install decoupler==1.6.0
RUN /opt/miniconda/bin/python -m pip3 install omnipath==1.0.8
RUN /opt/miniconda/bin/python -m pip3 install harmonypy==0.0.9  
RUN /opt/miniconda/bin/python -m pip3 install muon==0.1.6
RUN /opt/miniconda/bin/python -m pip3 install gdown==5.1.0 
RUN /opt/miniconda/bin/python -m pip3 install wget==3.2
RUN /opt/miniconda/bin/python -m pip3 install rapids-singlecell==0.10.0


############
### TEST ###

# list conda packages
RUN conda list > /logs/log_install_conda.txt

