# Test installation of packages

library("rmarkdown")
library("tidyverse")
library("reticulate")
library("reshape2")
library("Matrix.utils")
library("Matrix")
library("data.table")
library("readr")
library("R.utils")
library("useful")
library("Rmisc")
library("stringdist")
library("janitor")
library("xlsx")
library("openxlsx2")
library("easyPubMed")

library("RColorBrewer")
library("pheatmap")
library("ggrepel")
library("ggthemes")
library("ggnewscale")
library("gplots")
library("ggbeeswarm")
library("ggsignif")
library("ggpubr")
library("ggVennDiagram")
library("ggExtra")
library("ggsci")
library("UpSetR")
library("aplot")
library("alluvial")
library("ggalluvial")
library("circlize")
library("viridis")
library("magick")
library("factoextra")
library("gridExtra")
library("multipanelfigure")
library("patchwork")

library("corrplot")
library("dunn.test")
library("DirichletReg")
library("multcomp")

library("Seurat")
library("tidyseurat")
library("SoupX")
library("igraph")
library("rliger")
library("harmony")
library("symphony")
library("doRNG")
library("sleepwalk")
library("tidydr")
library("dsb")
library("clustree")
library("scCustomize")
library("seqinr")

library("Rsubread")
library("ShortRead")
library("dupRadar")
library("rtracklayer")
library("GenomicRanges")
library("Gviz")
library("Biostrings")

library("tximport")
library("tximeta")
library("DESeq2")
library("vsn")
library("IHW")
library("apeglm")
library("limma")
library("edgeR")
library("sva")

library("biomaRt")
library("orthogene")
library("GSVA")
library("GSEABase")
library("fgsea")
library("clusterProfiler")
library("gage")
library("DOSE")
library("KEGGgraph")
library("TSCAN")
library("RcisTarget")
library("escape")

library("ComplexHeatmap")
library("ggtree")
library("EnhancedVolcano")

library("rhdf5")
library("SingleCellExperiment")
library("SummarizedExperiment")
library("scuttle")
library("scran")
library("scater")
library("LoomExperiment")
library("monocle")
library("AUCell")
library("UCell")
library("SingleR")
library("MAST")
library("slingshot")
library("multtest")
library("muscat")
library("dittoSeq")
library("mumosa")
library("screenCounter")
library("TrajectoryUtils")

library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("org.Hs.eg.db")
library("EnsDb.Hsapiens.v86")
library("celldex")

library("SeuratWrappers")
library("DoubletFinder")
library("SeuratDisk")
library("leidenbase")
library("monocle3")
library("lisi")

library("nichenetr")
library("scPred")
library("sceasy")
library("VISION")
library("compassR")
library("cicero")
library("fastSave")
library("presto")
library("sceptre")

library("TFBSTools")
library("universalmotif")
library("DiffBind")
library("ChIPseeker")
library("chromVAR")
library("motifmatchr")
library("ArchR")
library("Signac")

library("cytoverse")
library("flowCore")
library("flowStats")
library("CytoML")
library("flowWorkspace")
library("ggcyto")
library("openCyto")
library("cydar")
library("CytoExploreR")

library("future") # future versions are no longer downgraded. Let's see if seurat parallelization still works ...
library("future.apply")

library("WGCNA")

sessionInfo()

writeLines(capture.output(sessionInfo()), "/logs/log_install_R.txt")
